### ISSUE TITLE
Set defaults for input

### ISSUE THREAD

**Issue by egrace479** [Imageomics/sum-buddy#1]
Would probably be good to at least have a default output filename and location.

If input is going to have a default (most logical is current directory), need to keep in mind and address the issue of it taking the checksum of itself (since it writes as it goes, it becomes the last file with all other files written).

**Comment by thompsonmj** [comment]
With #8, it explicitly skips hashing of the output file. 

Should the default output filepath be `<input_directory>/<input_directory>_checksums.csv`?

**Comment by egrace479** [comment]
I would think `<input_directory>_checksums.csv` in the directory above the `<input_directory>`, though I realize that would be problematic if `<input_directory>` is the root of the filesystem (or root that they have access to).

**Comment by thompsonmj** [comment]
With #8, the default output is `stdout`. Do we still want a default input, or keep the required positional argument for an input directory?
@hlapp, what do you think as well?

**Comment by egrace479** [comment]
I like `stdout` as the default when an output directory isn't provided; it's logical.

**Comment by hlapp** [comment]
The most logical default for input would, I think, be `.`, i.e., the current directory. But it's not too hard to state that as the final argument, and there's something to be said for inputs to be more explicit in a command line history, so I'd lean to require the user to specify it.

@egrace479 I think Matt was asking about the default for input, not output?

**Comment by thompsonmj** [comment]
OK, I consider this to be resolved then with a default for the output going to `stdout` (as brought up in the [first comment](https://github.com/Imageomics/sum-buddy/issues/1#issue-2306902097)) and requiring the user to specify a directory.
